version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    build:
      context: ./redis
    environment:
      REDIS_PASSWORD: "hard_password"

  nginx:
    build:
      context: ./nginx
    ports:
      - "8089:8089"